import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

// API Slice using Redux Toolkit Query
export const bannersApi = createApi({
  reducerPath: "bannersApi",
  baseQuery: fetchBaseQuery({
    baseUrl: `${process.env.NEXT_PUBLIC_APP_BASE_URL}/api/`,
  }),
  endpoints: (builder) => ({
    fetchBanners: builder.query({
      query: (lang) => ({
        url: "banners",
        headers: {
          lang: lang,
        },
      }),
      staleTime: 1000 * 60 * 5,
    }),
  }),
});

// Export the hook generated by RTK Query
export const { useFetchBannersQuery } = bannersApi;
