import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

// API Slice using Redux Toolkit Query
export const clientsApi = createApi({
  reducerPath: "clientsApi",
  baseQuery: fetchBaseQuery({
    baseUrl: `${process.env.NEXT_PUBLIC_APP_BASE_URL}/api/`,
  }),
  endpoints: (builder) => ({
    fetchClients: builder.query({
      query: (lang) => ({
        url: "clients",
        headers: {
          lang: lang,
        },
      }),
    }),
  }),
});

// Export the hook generated by RTK Query
export const { useFetchClientsQuery } = clientsApi;
